<footer class="footer grid__row ">
    <div class="footer__contatti  grid__col  grid__col--w50">
        <h1><img src="Asset/Img/logoNero.svg" alt="New or Review design" title="New or Review design" /></h1>
        <ul>
            <li><a href="http://www.nor-design.com" title="www.nor-design.com">www.nor-design.com</a></li>
            <li><a href="mailto:info@nor-design.com" title="send mail to info@nor-design.com ">info@nor-design.com</a></li>
            <li><a href="tel:+39 3337931450" title="call me to +39 3337931450">+39 3337931450</a></li>
        </ul>
    </div>

    <div class="footer__seo  grid__col  grid__col--w50 ">
        <ul class="footer__seo__link">
            <li><a href="" title="Progetti">Progetti</a></li>
            <li><a href="" title="Chi sono">Chi sono</a></li>
            <li><a href="" title="Contatti">Contatti</a></li>
        </ul>

        <h1 class="footer__seo__hidden">Social</h1>
        <ul class="footer__seo__socialLink">
            <li><i class="fa fa-linkedin-square"></i></li>
            <li><i class="fa fa-pinterest-square"></i></li>
            <li><i class="fa fa-instagram"></i></li>
        </ul>

        <p class="footer__seo__copy">&copy; <?php echo date("Y"); ?> New or Review design</p>

    </div>
</footer>