<header class="[ header  <?php echo (isset($hidden_header)) ? $hidden_header : ''; ?> ] [ grid_row ]">
    <h1 class="[ header__logo ] [ grid_col grid_col_w50 ]">
        <img src="Asset/Img/logoNero.svg" alt="New or Review design" title="New or Review design" />
    </h1>
    <nav class="[ header__nav ] [ grid_col grid_col_w50 ]">
        <ul>
            <li><a href="" title="Progetti">Progetti</a></li>
            <li><a href="" title="Chi sono">Chi sono</a></li>
            <li><a href="" title="Contatti">Contatti</a></li>
        </ul>
    </nav>
</header>