    <head>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="description" content="New or Review design : il sito di Serena Negri Cassano" />
        <meta name="keywords" content="design, interior design, home made, restauro" />
        <meta name="author" content="alessandro.balza@gmail.com" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title><?=TITLE_SITE?> | <?=$title_page?></title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
        <link rel="stylesheet" href="<?=MEDIA_URL?>/Css/style.css">
        <script type="text/javascript" src="<?=MEDIA_URL?>/Js/jquery-2.2.0.min.js"></script>
        <!--[if IE]><script type="text/javascript" src="<?=MEDIA_URL?>/Js/html5.js"></script><![endif]-->
        <script type="text/javascript" src ="<?=MEDIA_URL?>/Js/script.js"></script>

    </head>